import yfinance as yf
import pandas as pd

def fetch_market_data(ticker_symbol, interval="1m"):
    """
    Husnain APEX - Real-time Market Data Fetcher
    """
    try:
        # Determine period based on timeframe interval
        period = "1d" if interval in ["1m", "5m", "15m"] else "5d"
        
        # Fetch data from yfinance
        data = yf.download(tickers=ticker_symbol, period=period, interval=interval, progress=False)
        
        if data.empty:
            return None
            
        # Clean multi-level columns if generated by yfinance
        if isinstance(data.columns, pd.MultiIndex):
            data.columns = data.columns.get_level_values(0)
            
        return data
    except Exception as e:
        print(f"Data Fetching Error: {e}")
        return None